<a href="https://colab.research.google.com/github/smart4ghari/Data_Science/blob/main/4_1_Numpy_Examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy

In [ ]:
import numpy as np

#### Arange function

* As the name represents it's like a range function which is used to give a range of numbers

In [ ]:
arr1 = np.arange(10,21,2)  # parameters are start pos, stop pos, step
arr1

array([10, 12, 14, 16, 18, 20])

In [ ]:
arr1 = np.arange(12)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# Reshape function used to reshape the structure
arr2 = arr1.reshape(6,2)  # Here reshape function will change it into 6 rows 2 columns
arr2

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
arr2 = arr1.reshape(3,2,2)
arr2

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [ ]:
arr2[...,0]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [ ]:
arr2[1:,...]

array([[[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [ ]:
arr3 = np.array([
    [1,2,3,4,5],
    [11,22,33,44,55],
    [10,20,30,40,50],
    [21,23,25,27,29]
])

In [ ]:
# Get the first index of the given array
arr3[0]

# The output will gives the entire row

array([1, 2, 3, 4, 5])

In [ ]:
# If we need only the first element then we need to give it in matrix format
arr3[0,0]  # Get the 0th row and 0th column

1

In [ ]:
# If we need second element use like this
arr3[0,1]

2

In [ ]:
i = np.array([0,1,2,1])
j = np.array([1,2,3,4])

In [ ]:
arr3

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55],
       [10, 20, 30, 40, 50],
       [21, 23, 25, 27, 29]])

In [ ]:
arr3[i,j]

array([ 2, 33, 40, 55])

### Explanation for the above operation

Let's break down the provided code snippet:

```python
arr3 = np.array([
    [1, 2, 3, 4, 5],
    [11, 22, 33, 44, 55],
    [10, 20, 30, 40, 50],
    [21, 23, 25, 27, 29]
])

i = np.array([0, 1, 2, 1])
j = np.array([1, 2, 3, 4])

result = arr3[i, j]
```

Explanation:

1. `arr3`: This is a 4x5 NumPy array created using `np.array()`. It's a 2D array with integer values.

2. `i` and `j`: These are 1D NumPy arrays representing indices. `i` contains row indices, and `j` contains column indices.

3. `arr3[i, j]`: This code uses fancy indexing to select elements from the `arr3` array. It selects elements at positions defined by pairs of corresponding elements in `i` and `j`. In this case, it selects the following elements:
   - `arr3[0, 1]` (first row, second column)
   - `arr3[1, 2]` (second row, third column)
   - `arr3[2, 3]` (third row, fourth column)
   - `arr3[1, 4]` (second row, fifth column)

   The result is a 1D array containing these selected elements: `array([2, 33, 40, 55])`.

So, `result` will be the array `[2, 33, 40, 55]`.

In [ ]:
# Print all the elements which is less than 15 in arr3 array
arr3[arr3<15]

array([ 1,  2,  3,  4,  5, 11, 10])

In [ ]:
arr4 = np.array([True,False,True,False])
arr3[arr4,:]

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [ ]:
my_matrix = [[1,2,3,4,5],
            [6,7,8,9,10],
            [11,12,13,14,15]]

# Changing the list into numpy array

my_matrix1 = np.array(my_matrix)
my_matrix1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
type(my_matrix)

list

In [ ]:
type(my_matrix1)

numpy.ndarray

In [ ]:
arr_zeros = np.zeros(10)
arr_zeros # gives 1d array of zeros as floating values

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr_zeros = np.zeros((3,3)) # Here I need 2d array with 3 rows and 3 columns
arr_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Work for you guys
* There's one similar function like np.zeros() but it'll produce another value as an output if we change the name of the function
* Let me know what's that one😊

### Linspace

Gives linearly spaced numbers

In [ ]:
arr_ls = np.linspace(0,11,3)
arr_ls

array([ 0. ,  5.5, 11. ])

`np.linspace` is a function in NumPy that creates an array of evenly spaced values over a specified range. The syntax for `np.linspace` is as follows:

```python
import numpy as np

# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
```

- `start`: The starting value of the sequence.
- `stop`: The end value of the sequence.
- `num`: The number of evenly spaced samples to generate. Default is 50.
- `endpoint`: If True (default), `stop` is the last value in the range. If False, `stop` is not included.
- `retstep`: If True, return `(array, step)`, where `step` is the spacing between values.
- `dtype`: The data type of the output array. If not specified, the data type is inferred from the input values.

Here's an example of using `np.linspace`:

```python
import numpy as np

# Create an array of 10 evenly spaced values from 0 to 1 (inclusive)
my_array = np.linspace(0, 1, num=10)

print(my_array)
```

In this example, `my_array` will contain 10 evenly spaced values between 0 and 1, inclusive. The output might look something like this:

```
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
```

This is useful when you need a specified number of points within a given range for various applications, such as plotting or numerical simulations.

### Creating Identity matrix

In [ ]:
id_matrix = np.eye(5,dtype = int)
id_matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
# Creating a numpy array with random values between 0 to 1
rand1 = np.random.rand(3,3) # Here it'll produce 3x3 matrix
rand1

array([[0.35842494, 0.39068971, 0.59538467],
       [0.42640497, 0.53842301, 0.38895842],
       [0.34899948, 0.9892917 , 0.1510841 ]])

In [ ]:
# Here the values which the numpy array produces will be in standard normal distribution
rand2 = np.random.randn(3,3)
rand2

array([[ 0.24397703,  1.31627926, -0.61336727],
       [ 0.96036836, -0.64044464, -0.74151654],
       [ 2.3618761 , -0.02488661, -0.8102475 ]])

In [ ]:
# In the below method the numpy array will produce random integers
rand3 = np.random.randint(0,100,10)
# In the above code we've given starting pos as 0, ending pos as 100 and need 10 random integer at last
# So it'll produce the 10 random integers within the given range
rand3

array([61, 80, 35, 78, 14, 60, 47, 24, 33, 56])

In [ ]:
# Creating a 2d matrix

rand4 = np.random.randint(10,20,(5,5))
rand4

array([[11, 12, 17, 16, 10],
       [18, 12, 14, 10, 12],
       [11, 11, 10, 18, 17],
       [13, 11, 12, 14, 11],
       [16, 18, 19, 14, 15]])

In [ ]:
np.random.seed(42)  # seed allows us to set a particular set of random number
np.random.rand(4)   # Whenever we execute this one we'll get same set of values

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
ran5 = np.random.randint(0,101,20)
print(ran5)

# finding the max value
print("Maximum value is:",ran5.max())

# finding the minimum value.
print("Minimum value is:",ran5.min())

# finding the index value of maximum value
print("Index of Maximum is:",ran5.argmax())

# finding the index value of minimum value
print("Index of Minimum is:",ran5.argmin())

[46 34 77 80 35 49  3  1  5 53  3 53 92 62 17 89 43 33 73 61]
Maximum value is: 92
Minimum value is: 1
Index of Maximum is: 12
Index of Minimum is: 7


In [ ]:
print(ran5.shape)   # Here shape is an attribute not a method

(20,)


In [ ]:
ran5 = ran5.reshape(5,4)
print(ran5)

[[46 34 77 80]
 [35 49  3  1]
 [ 5 53  3 53]
 [92 62 17 89]
 [43 33 73 61]]


### Indexing and selection on NumPy arrays

In [ ]:
arr5 = np.arange(0,11)
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# get the index value
arr5[4]

4

In [ ]:
# This indexing is more or less same as python list indexing
arr5[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr5[:9] # Here end position value will be ignored in slicing ( so in result we can able to see upto 8)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# If we need that value as well means add 1
arr5[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Reassinging the values from 0 to 4 th index
arr5[0:5] = 100 # Note : this can't be done in normal python lists
arr5

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr5 = np.arange(0,11)
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr5_chng = arr5[0:3]
arr5_chng

array([0, 1, 2])

In [ ]:
arr5_chng[:] = 20
arr5_chng

array([20, 20, 20])

In [ ]:
# It's recommended to use copy method before changing the original array so that original array gets unaffected
arr5_cpy = arr5.copy()
arr5_cpy

array([20, 20, 20,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr5_cpy[:] = 100
arr5_cpy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
# Here the original array is arr5 let's see whether it got affected or not
arr5

array([20, 20, 20,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# 2d arrays

_2d = np.array([[1,2,3,4],
                [5,6,6,7],
                [99,100,101,102]])
_2d

array([[  1,   2,   3,   4],
       [  5,   6,   6,   7],
       [ 99, 100, 101, 102]])

In [ ]:
_2d.shape # it's a 3 by 4 matrix

(3, 4)

In [ ]:
_2d[0] # gives the entire 1st row

array([1, 2, 3, 4])

In [ ]:
_2d[0][0]

1

In [ ]:
_2d[1][3]  # get the value of 2nd row and 4th column

7

In [ ]:
_2d[2][1]  # get the value of 3rd row and 2nd column

100

In [ ]:
bool_arr = np.arange(0,10)
bool_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
bool_arr1 = bool_arr > 7
bool_arr1

array([False, False, False, False, False, False, False, False,  True,
        True])

In [ ]:
bool_arr[bool_arr1]

array([8, 9])

### NumPy operations

In [ ]:
new_arr = np.arange(0,50,5)
new_arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
new_arr * 2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
new_arr / 10

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
# zero division error, but numpy handles in different way
new_arr / 0

C:\Users\munee\AppData\Local\Temp\ipykernel_3732\1508088097.py:1: RuntimeWarning: divide by zero encountered in divide
  new_arr / 0
C:\Users\munee\AppData\Local\Temp\ipykernel_3732\1508088097.py:1: RuntimeWarning: invalid value encountered in divide
  new_arr / 0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [ ]:
# This is how the normal python error would be there
1 / 0

ZeroDivisionError: division by zero

In [ ]:
# Getting the square root value of our array
sqrt_arr = np.sqrt(new_arr)
sqrt_arr

array([0.        , 2.23606798, 3.16227766, 3.87298335, 4.47213595,
       5.        , 5.47722558, 5.91607978, 6.32455532, 6.70820393])

In [ ]:
sin_arr = np.sin(new_arr)
sin_arr

array([ 0.        , -0.95892427, -0.54402111,  0.65028784,  0.91294525,
       -0.13235175, -0.98803162, -0.42818267,  0.74511316,  0.85090352])

In [ ]:
sum_arr = np.sum(arr5)
sum_arr

112

In [ ]:
# summing up the rows
arr6 = np.arange(0,25).reshape(5,5)
sum_arr = np.sum(arr6,axis = 0) # adding the rows
sum_arr

array([50, 55, 60, 65, 70])

In [ ]:
sum_arr1 = np.sum(arr6,axis = 1) # adding the columns
sum_arr1

array([ 10,  35,  60,  85, 110])