<a href="https://colab.research.google.com/github/smart4ghari/Data_Science/blob/main/4_Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

In [ ]:
import numpy as np

In [ ]:
my_list = [1,2,3,4,5]
type(my_list)

list

In [ ]:
## Converting list to array
arr = np.array(my_list)
print(arr)

[1 2 3 4 5]


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
np.arange(3)

array([0, 1, 2])

In [ ]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In np.arange() the first argument will be always less than the second argument

In [ ]:
np.arange(20,10) # This is invalid

array([], dtype=int32)

In [ ]:
np.arange(10,10)

array([], dtype=int32)

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros([3,5],dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
n = (3,4) # 3 rows and 4 columns
np.zeros(n,dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.ones(n)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones(n,dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.random.rand(3,2)

array([[0.69050229, 0.84510636],
       [0.66905857, 0.43589531],
       [0.62994576, 0.98962211]])

In [ ]:
np.random.randint(4,5)

4

In [ ]:
np.random.randint(1,500)

423

In [ ]:
np.random.randn(200,899)

array([[-0.93713968, -0.21273127,  0.16164789, ...,  0.07870192,
         0.24704573,  0.04970815],
       [ 0.85641918, -0.03585561, -2.14576012, ...,  0.88263355,
         0.4228943 ,  0.64878641],
       [ 0.78340917,  0.75049117,  0.75240909, ..., -0.69355858,
         0.58301701,  0.0843069 ],
       ...,
       [-0.14398268,  1.53536845,  0.90930985, ..., -0.58350968,
        -1.0165124 , -1.03507083],
       [ 0.34853679, -0.81060042, -1.17978135, ..., -0.5311586 ,
         1.41880689, -0.34020841],
       [-0.21031882, -2.14808457, -0.94339323, ..., -0.15443582,
         0.87681879, -0.97771581]])